### ISSUE TITLE
Code of Conduct 

### ISSUE THREAD

**Issue by vovan47** [mbelsky/js-problems#2]
I've noticed you don't have a CoC yet. Care to accept one? I would suggest accepting NCoC CoC, believe me it's an incredible CoC, everyone should accept it or at least try it. You would be amazed how great of a CoC it is.

Here is how you can accept a CoC: https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

Please do, okay?

**Comment by letalumil** [comment]
@vovan47 I would be very happy to accept your CoC if I was the owner of the project.
